name: Build Android App

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code

      uses: actions/checkout@v2

    - name: Setup JDK

      uses: actions/setup-java@v1

      with:

        java-version: '11'

    - name: Grant execute permission to gradlew

      run: chmod +x gradlew

    - name: Build App

      run: ./gradlew assembleDebug

    - name: Archive Artifacts

      uses: actions/upload-artifact@v2

      with:

        name: app

        path: app/build/outputs/apk/debug/app-debug.apk

